[package]
name = "noierrdev-solana-keypair-converter"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
serde = "1.0.217"
serde_json = "1.0.135"
tokio = {version="1.43.0" , features = ["full"]}
solana-sdk = "2.1.7"
anyhow = "1.0.95"
